import { Router } from 'express';
import { z } from 'zod';
import puppeteer from 'puppeteer-core';
import * as fs from 'fs';
import * as path from 'path';
import { getDb } from '../../db';
import * as launcher from '../../launcher/chromium';
import { PROFILES_DIR } from '../../config';
import {
  readCookieDb,
  mergeCookiesToDb,
  getProfileCookiesPath,
  getProfileOsKey,
  CookieRow,
} from '../../io/cookieSqlite';

const router = Router();

/**
 * Parse a Netscape cookies.txt line into the CDP cookie format.
 * Format (tab-separated, 7 fields):
 *   domain  includeSubdomains  path  secure  expiry  name  value
 * Lines starting with # are comments; blank lines are skipped.
 */
export function parseNetscapeLine(line: string): Record<string, unknown> | null {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) return null;
  const parts = trimmed.split('\t');
  if (parts.length < 7) {
    // some exporters use whitespace; fall back to multi-space split
    const ws = trimmed.split(/\s{2,}/);
    if (ws.length < 7) return null;
    parts.length = 0;
    parts.push(...ws);
  }
  const [domain, , path, secure, expiry, name, value] = parts.map((p) => p.trim());
  if (!domain || !name) return null;
  const cookie: Record<string, unknown> = {
    name,
    value,
    domain,
    path: path || '/',
    secure: secure.toUpperCase() === 'TRUE',
    httpOnly: false,
  };
  const exp = Number(expiry);
  if (Number.isFinite(exp) && exp > 0) {
    cookie.expires = exp; // CDP expects seconds since epoch
  }
  return cookie;
}

/** Parse a whole Netscape cookies.txt document. */
export function parseNetscape(text: string): Array<Record<string, unknown>> {
  const out: Array<Record<string, unknown>> = [];
  for (const line of text.split(/\r?\n/)) {
    const cookie = parseNetscapeLine(line);
    if (cookie) out.push(cookie);
  }
  return out;
}

/** Render CDP-format cookies as a Netscape cookies.txt document. */
export function toNetscape(cookies: Array<Record<string, unknown>>): string {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by NullTrace', ''];
  for (const c of cookies) {
    const domain = String(c.domain ?? '');
    const includeSub = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = String(c.path ?? '/');
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expiresRaw = c.expires;
    const expires =
      typeof expiresRaw === 'number' && expiresRaw > 0
        ? Math.round(expiresRaw)
        : Math.round(Date.now() / 1000) + 31536000; // session-less fallback: +1 year
    const name = String(c.name ?? '');
    const value = String(c.value ?? '');
    lines.push([domain, includeSub, path, secure, String(expires), name, value].join('\t'));
  }
  return lines.join('\n') + '\n';
}

function parseSqlitePayload(text?: string, sqliteBase64?: string): Buffer | null {
  const raw = sqliteBase64 || text || '';
  if (!raw) return null;
  if (raw.startsWith('SQLite format 3')) {
    return Buffer.from(raw, 'latin1');
  }
  const b64Buf = Buffer.from(raw.trim(), 'base64');
  if (b64Buf.subarray(0, 15).toString('latin1') === 'SQLite format 3') {
    return b64Buf;
  }
  return Buffer.from(raw, 'latin1');
}

const importSchema = z.object({
  user_id: z.string(),
  cookies: z.array(z.record(z.unknown())).optional(),
  format: z.enum(['json', 'netscape', 'sqlite', 'cookies']).optional(),
  text: z.string().optional(),
  sqlite_base64: z.string().optional(),
});

/*
 * `target_dir` was removed from the cookie import/export surface.
 *
 * It accepted a caller-supplied directory, used it verbatim as the profile directory, and then
 * `mkdirSync` + `writeFileSync`'d a SQLite file at `getProfileCookiesPath(thatDir)`. Nothing
 * needed it: the renderer, the SDK and the MCP server never send it, and the only callers were two
 * tests that passed a temp dir solely to exercise the running-profile guard — which the ordinary
 * `user_id` path exercises just as well.
 *
 * Keeping it with a containment check was the alternative. Removing it is better: a cookie database
 * belongs to a profile, the profile's directory is derived from `user_id`, and a field that lets a
 * caller choose the destination is a write primitive with no legitimate consumer. The path is now
 * always inside `PROFILES_DIR`, so there is no escape to guard against.
 */
function profileDirForCookies(userId: string): string {
  /*
   * The id is resolved and then CONTAINED, rather than joined blindly.
   *
   * `path.join(ROOT, userId)` does not defend itself: `path.join('/data/profiles', '../../Windows/
   * System32')` yields `/data/Windows/System32`, so a traversing id would place the cookie database
   * outside the profiles tree. The route only reaches here after `SELECT id FROM profiles WHERE
   * id = ?` succeeds, and ids are generated as `p_<uuid>` — but defense in depth still
   * applies: the id comes from stored data, not a fresh uuid call at this point, so containing
   * the result costs one comparison and removes the assumption entirely.
   */
  const root = path.resolve(PROFILES_DIR);
  const resolved = path.resolve(root, userId);
  const rootWithSep = root.endsWith(path.sep) ? root : root + path.sep;
  if (resolved !== root && !resolved.startsWith(rootWithSep)) {
    throw new Error('profile id resolves outside the profiles directory');
  }
  return resolved;
}

router.post('/api/v1/browser-profile/cookies/import', async (req, res) => {
  const parsed = importSchema.safeParse(req.body);
  if (!parsed.success) {
    res.json({ code: -1, msg: 'invalid body', data: { errors: parsed.error.flatten() } });
    return;
  }
  const userId = parsed.data.user_id;

  const db = getDb();
  const profile = db.prepare('SELECT id FROM profiles WHERE id = ?').get(userId);
  if (!profile) {
    res.json({ code: -1, msg: 'profile not found', data: {} });
    return;
  }

  // SQLite import path
  if (parsed.data.format === 'sqlite' || parsed.data.format === 'cookies' || parsed.data.sqlite_base64) {
    if (launcher.isRunning(userId)) {
      res.json({ code: -1, msg: 'profile is currently running', data: {} });
      return;
    }

    const sqliteBuffer = parseSqlitePayload(parsed.data.text, parsed.data.sqlite_base64);
    if (!sqliteBuffer) {
      res.json({ code: -1, msg: 'sqlite payload is required', data: {} });
      return;
    }

    const profileDir = profileDirForCookies(userId);
    const osKey = getProfileOsKey(profileDir);
    const incomingCookies = await readCookieDb(sqliteBuffer, osKey);

    const targetCookiesPath = getProfileCookiesPath(profileDir);
    let existingBytes: Buffer | null = null;
    if (fs.existsSync(targetCookiesPath)) {
      existingBytes = fs.readFileSync(targetCookiesPath);
    }

    const mergedDbBytes = await mergeCookiesToDb(existingBytes, incomingCookies, osKey);
    fs.mkdirSync(path.dirname(targetCookiesPath), { recursive: true });
    fs.writeFileSync(targetCookiesPath, mergedDbBytes);

    const updatedCookies = await readCookieDb(mergedDbBytes, osKey);
    db.prepare('UPDATE profiles SET cookies_json = ?, updated_at = ? WHERE id = ?').run(
      JSON.stringify(updatedCookies),
      Date.now(),
      userId
    );

    res.json({ code: 0, msg: 'success', data: { count: incomingCookies.length } });
    return;
  }

  // Two input shapes: structured cookies[] (json) or raw text (netscape).
  let cookies: Array<Record<string, unknown>> | undefined = parsed.data.cookies;
  if (parsed.data.format === 'netscape' || (!cookies && parsed.data.text)) {
    if (!parsed.data.text) {
      res.json({ code: -1, msg: 'text is required for netscape format', data: {} });
      return;
    }
    cookies = parseNetscape(parsed.data.text);
    if (cookies.length === 0) {
      res.json({ code: -1, msg: 'no valid cookies found in netscape text', data: {} });
      return;
    }
  }
  if (!cookies || cookies.length === 0) {
    res.json({ code: -1, msg: 'cookies[] or text is required', data: {} });
    return;
  }

  db.prepare('UPDATE profiles SET cookies_json = ?, updated_at = ? WHERE id = ?').run(
    JSON.stringify(cookies),
    Date.now(),
    parsed.data.user_id
  );
  res.json({ code: 0, msg: 'success', data: { count: cookies.length } });
});

router.post('/api/v1/browser-profile/cookies/import-sqlite', async (req, res) => {
  const parsed = importSchema.safeParse(req.body);
  if (!parsed.success) {
    res.json({ code: -1, msg: 'invalid body', data: { errors: parsed.error.flatten() } });
    return;
  }
  const userId = parsed.data.user_id;
  if (launcher.isRunning(userId)) {
    res.json({ code: -1, msg: 'profile is currently running', data: {} });
    return;
  }

  const db = getDb();
  const profile = db.prepare('SELECT id FROM profiles WHERE id = ?').get(userId);
  if (!profile) {
    res.json({ code: -1, msg: 'profile not found', data: {} });
    return;
  }

  const sqliteBuffer = parseSqlitePayload(parsed.data.text, parsed.data.sqlite_base64);
  if (!sqliteBuffer) {
    res.json({ code: -1, msg: 'sqlite payload is required', data: {} });
    return;
  }

  const profileDir = profileDirForCookies(userId);
  const osKey = getProfileOsKey(profileDir);
  const incomingCookies = await readCookieDb(sqliteBuffer, osKey);

  const targetCookiesPath = getProfileCookiesPath(profileDir);
  let existingBytes: Buffer | null = null;
  if (fs.existsSync(targetCookiesPath)) {
    existingBytes = fs.readFileSync(targetCookiesPath);
  }

  const mergedDbBytes = await mergeCookiesToDb(existingBytes, incomingCookies, osKey);
  fs.mkdirSync(path.dirname(targetCookiesPath), { recursive: true });
  fs.writeFileSync(targetCookiesPath, mergedDbBytes);

  const updatedCookies = await readCookieDb(mergedDbBytes, osKey);
  db.prepare('UPDATE profiles SET cookies_json = ?, updated_at = ? WHERE id = ?').run(
    JSON.stringify(updatedCookies),
    Date.now(),
    userId
  );

  res.json({ code: 0, msg: 'success', data: { count: incomingCookies.length } });
});

router.get('/api/v1/browser-profile/cookies/export', async (req, res) => {
  const userId = String(req.query.user_id || '');
  const format = String(req.query.format || 'json').toLowerCase();

  const db = getDb();
  const profile = db
    .prepare('SELECT id, cookies_json FROM profiles WHERE id = ?')
    .get(userId) as { id: string; cookies_json: string | null } | undefined;
  if (!profile) {
    res.json({ code: -1, msg: 'profile not found', data: {} });
    return;
  }

  // SQLite export path
  if (format === 'sqlite' || format === 'cookies') {
    if (launcher.isRunning(userId)) {
      res.json({ code: -1, msg: 'profile is currently running', data: {} });
      return;
    }

    const profileDir = profileDirForCookies(userId);
    const cookiesPath = getProfileCookiesPath(profileDir);
    const osKey = getProfileOsKey(profileDir);

    let sqliteBytes: Buffer;
    if (fs.existsSync(cookiesPath)) {
      sqliteBytes = fs.readFileSync(cookiesPath);
    } else {
      let storedCookies: CookieRow[] = [];
      if (profile.cookies_json) {
        try {
          const parsed = JSON.parse(profile.cookies_json);
          if (Array.isArray(parsed)) storedCookies = parsed;
        } catch {
          // ignore
        }
      }
      sqliteBytes = await mergeCookiesToDb(null, storedCookies, osKey);
    }

    res.setHeader('Content-Type', 'application/x-sqlite3');
    res.setHeader('Content-Disposition', 'attachment; filename="Cookies"');
    res.send(sqliteBytes);
    return;
  }

  // If the profile is running, read live cookies via CDP.
  let cookies: unknown[] = [];
  let source = 'stored';
  if (launcher.isRunning(userId)) {
    const ws = launcher.getRunningWs(userId);
    if (ws) {
      try {
        const browser = await puppeteer.connect({ browserWSEndpoint: ws, defaultViewport: null });
        try {
          const targets = await browser.targets();
          const pageTarget = targets.find((t) => t.type() === 'page');
          if (pageTarget) {
            const session = await pageTarget.createCDPSession();
            const result = (await session.send('Network.getAllCookies')) as { cookies: unknown[] };
            await session.detach().catch(() => undefined);
            cookies = result.cookies;
            source = 'live';
          }
        } finally {
          browser.disconnect();
        }
      } catch {
        // fall through to stored cookies
      }
    }
  }

  if (source === 'stored' && profile.cookies_json) {
    try {
      const parsed = JSON.parse(profile.cookies_json);
      if (Array.isArray(parsed)) cookies = parsed;
    } catch {
      // ignore invalid JSON
    }
  }

  // format=netscape returns a ready-to-save cookies.txt document
  if (format === 'netscape') {
    const text = toNetscape(cookies as Array<Record<string, unknown>>);
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="cookies-${userId}.txt"`
    );
    res.send(text);
    return;
  }

  res.json({ code: 0, msg: 'success', data: { cookies, source } });
});

router.get('/api/v1/browser-profile/cookies/export-sqlite', async (req, res) => {
  const userId = String(req.query.user_id || '');

  if (launcher.isRunning(userId)) {
    res.json({ code: -1, msg: 'profile is currently running', data: {} });
    return;
  }

  const db = getDb();
  const profile = db
    .prepare('SELECT id, cookies_json FROM profiles WHERE id = ?')
    .get(userId) as { id: string; cookies_json: string | null } | undefined;
  if (!profile) {
    res.json({ code: -1, msg: 'profile not found', data: {} });
    return;
  }

  const profileDir = profileDirForCookies(userId);
  const cookiesPath = getProfileCookiesPath(profileDir);
  const osKey = getProfileOsKey(profileDir);

  let sqliteBytes: Buffer;
  if (fs.existsSync(cookiesPath)) {
    sqliteBytes = fs.readFileSync(cookiesPath);
  } else {
    let storedCookies: CookieRow[] = [];
    if (profile.cookies_json) {
      try {
        const parsed = JSON.parse(profile.cookies_json);
        if (Array.isArray(parsed)) storedCookies = parsed;
      } catch {
        // ignore
      }
    }
    sqliteBytes = await mergeCookiesToDb(null, storedCookies, osKey);
  }

  res.setHeader('Content-Type', 'application/x-sqlite3');
  res.setHeader('Content-Disposition', 'attachment; filename="Cookies"');
  res.send(sqliteBytes);
});

export default router;
